title: Deeraj Nair
logo: /assets/img/headshot.png
description: Passionate about transforming data into actionable insights. Skilled in predictive modeling, data visualization, and machine learning, with a focus on supply chain optimization. Dedicated to creating impactful, data-driven solutions.
show_downloads: false
theme: jekyll-theme-minimal
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/deeraj-nair-1a7403214/
  - name: GitHub
    url: https://github.com/deeraj44
  - name: Email
    url: mailto:deerajnair44@gmail.com

